module.exports = {
  ci: {
    collect: {
      url: ['http://localhost:3000'],
      startServerCommand: 'npm start',
      startServerReadyPattern: 'Local:',
      startServerReadyTimeout: 10000,
    },
    assert: {
      assertions: {
        'categories:performance': ['warn', { minScore: 0.8 }],
        'categories:accessibility': ['error', { minScore: 0.9 }],
        'categories:best-practices': ['warn', { minScore: 0.8 }],
        'categories:seo': ['warn', { minScore: 0.8 }],
        'categories:pwa': ['error', { minScore: 0.9 }],
        'service-worker': 'error',
        'manifest-display': 'error',
        'manifest-name': 'error',
        'manifest-short-name': 'error',
        'manifest-description': 'error',
        'manifest-start-url': 'error',
        'manifest-theme-color': 'error',
        'manifest-background-color': 'error',
        'manifest-icons': 'error',
        'apple-touch-icon': 'error',
        'maskable-icon': 'error',
        'offline-start-url': 'error',
        'works-offline': 'error',
        'viewport': 'error',
        'without-javascript': 'error',
        'redirects-http': 'error',
        'uses-https': 'error',
        'uses-long-cache-ttl': 'error',
        'total-byte-weight': ['warn', { maxNumericValue: 500000 }],
        'dom-size': ['warn', { maxNumericValue: 1500 }],
        'critical-request-chains': ['warn', { maxLength: 5 }],
        'render-blocking-resources': ['warn', { maxLength: 2 }],
        'unused-css-rules': ['warn', { maxLength: 10 }],
        'unused-javascript': ['warn', { maxLength: 10 }],
        'efficient-animated-content': 'error',
        'preload-lcp-image': 'error',
        'largest-contentful-paint': ['warn', { maxNumericValue: 2500 }],
        'first-contentful-paint': ['warn', { maxNumericValue: 1800 }],
        'cumulative-layout-shift': ['warn', { maxNumericValue: 0.1 }],
        'max-potential-fid': ['warn', { maxNumericValue: 130 }],
        'interactive': ['warn', { maxNumericValue: 3500 }],
      },
    },
    upload: {
      target: 'temporary-public-storage',
    },
  },
}; 